---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
  type: NodePort
  ports:
    - name: tomcat
      port: 8080
      nodePort: 30002
      protocol: TCP


